title: Saurabh Pratap Singh
email: saurabh.june8@gmail.com
description: >-
  Data Insights & BI Strategy Leader | Bayer Crop Science.
  Specializing in AgTech Data Strategy and ROI-driven Analytics.
theme: minima