title: Saurabh
email: saurabh.june8@gmail.com
description: >-
  Data Insights & BI Strategy Leader | Bayer Crop Science.
  Bridging AgTech Domain Expertise with ROI-driven Analytics.

# This is the "secret sauce" to make navigation look professional
header_pages:
  - about.md
  - projects.md

# This allows us to use custom CSS later if we want to move the sidebar
plugins:
  - jekyll-feed
  - jekyll-seo-tag