project:
  type: website
  output-dir: _site

website:
  title: "Decision Science Lab"
  description: "Bridging the gap between Business Intelligence and Decision Science."
  
  navbar:
    background: primary
    foreground: light
    left:
      - text: "Home"
        href: index.qmd
      - text: "Case Studies"
        href: reports.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: linkedin
        href: https://linkedin.com/
      - icon: github
        href: https://github.com/

format:
  html:
    theme: 
      light: cosmo
      dark: slate # We will force this to be default via script below for toggle support
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
        <script>mermaid.initialize({startOnLoad:true});</script>
        <script>
        // Force Dark Mode by default for new visitors
        if (localStorage.getItem("quarto-color-scheme") === null) {
            localStorage.setItem("quarto-color-scheme", "dark");
        }
        </script>